import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Header } from "./Header/Navbar";

export const metadata: Metadata = {
  title: "P'tits Créateurs",
  description: "Generated by create next app",
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <div className="flex h-screen flex-col">
        {/* Header reste en haut */}
        <div className="flex-none">
          <Header />
        </div>
        {/* Children occupe tout l'espace restant */}
        <div className="grow overflow-y-auto p-6 md:p-12">
          {children}
        </div>
      </div>
    </body>
  </html>
  );
}
